// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/eslint',
    '@nuxt/fonts',
    '@nuxt/icon',
    '@nuxt/image',
    '@nuxtjs/i18n',
    '@nuxtjs/seo',
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    '@nuxtjs/turnstile',
    '@pinia/nuxt',
    'dragon-editor',
    'nuxt-svgo-loader',
  ],
  ssr: true,
  devtools: { enabled: false },
  app: {
    baseURL: process.env.NUXT_APP_BASE_URL || '/',
    head: {
      titleTemplate: '%s %separator %siteName',
      templateParams: {
        separator: '|',
        siteName: 'NAS Crystal',
      },
    },
  },
  css: ['~/assets/main.scss'],
  site: {
    url: 'https://nascrystal.ru',
    name: 'NAS Crystal',
    description: 'NAS Crystal',
  },
  runtimeConfig: {
    public: {
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://nascrystal.ru',
      siteName: 'NAS Crystal',
      siteDescription: 'NAS Crystal',
    },
  },
  buildDir: '.nuxt/',
  devServer: {
    host: '127.0.0.1',
    port: 3000,
  },
  compatibilityDate: '2025-07-15',
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: `@use "@/assets/variables.scss" as *;`,
        },
      },
    },
  },
  eslint: {
    config: {
      stylistic: { semi: true, quotes: 'single', indent: 2 },
    },
  },
  fonts: {
    // assets: {
    //   prefix: '~/assets/fonts/',
    // },
    families: [
      { name: 'Inter',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/Inter-Thin.ttf',
        weight: 100,
      },
      { name: 'Inter',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/Inter-Light.ttf',
        weight: 300,
      },
      { name: 'Inter',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/Inter-Regular.ttf',
        weight: 500,
      },
      { name: 'Inter',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/Inter-Bold.ttf',
        weight: 800,
      },
      { name: 'Cormorant Garamond',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/CormorantGaramond-Bold.ttf',
        weight: 800,
      },
      { name: 'Cormorant Garamond',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/CormorantGaramond-Regular.ttf',
        weight: 500,
      },
      { name: 'Cormorant Garamond',
        provider: 'local',
        style: 'normal',
        global: true,
        src: '/assets/fonts/CormorantGaramond-Light.ttf',
        weight: 300,
      },
    ],
  },
  i18n: {
    baseUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://nascrystal.ru',
    lazy: true,
    langDir: 'locales',
    strategy: 'no_prefix',
    defaultLocale: 'ru',
    locales: [
      { code: 'ru', name: 'Русский', file: 'ru.json' },
      { code: 'en', name: 'English', file: 'en.json' },
    ],
    detectBrowserLanguage: false,
  },
  icon: {
    customCollections: [
      {
        prefix: 'nsc',
        dir: './public/icons',
        normalizeIconName: false,
      },
    ],
  },
  robots: {
    sitemap: 'https://nascrystal.ru/sitemap.xml',
    allow: process.env.NODE_ENV === 'production' ? '/' : [],
    disallow: process.env.NODE_ENV === 'production' ? [] : '/',
  },
  sitemap: {
    autoLastmod: true,
    xsl: false,
  },
});
